# Generated by Django 3.1.1 on 2020-09-23 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sku', models.CharField(max_length=150)),
                ('image', models.URLField()),
                ('images', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('desc_txt', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('url', models.URLField()),
                ('breadcrumbs', models.CharField(blank=True, max_length=200)),
                ('metaKeywords', models.CharField(max_length=200)),
                ('crawled_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ckk.shop')),
            ],
            options={
                'ordering': ['sku'],
            },
        ),
    ]
