# Generated by Django 3.1 on 2020-09-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0002_auto_20200924_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
