# Generated by Django 3.1 on 2020-09-28 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0004_category_ckkproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='subcat',
            new_name='subcategory',
        ),
        migrations.DeleteModel(
            name='CKKProduct',
        ),
    ]
